# LAB 01.01 - Practice submission

In [ ]:
!wget --no-cache -O init.py -q https://raw.githubusercontent.com/rramosp/ai4eng.v1/main/content/init.py
import init; init.init(force_download=False); init.get_weblink()

replicating local resources


In [ ]:
import inspect
from local.lib.rlxmoocapi import session
session.LoginSequence(endpoint=init.endpoint, course_id="ai4eng.v1.udea.r2", session_id="2023.1",lab_id="L01.01", varname="student");

logging in as santiago.ramirez10@udea.edu.co... please wait
using course session ai4eng.v1.udea.r2::2023.1
success!! you are logged in


### Ejercicio 1: Suma dos matrices

Completa la función `suma_matrices` para que, dadas dos arrays numpy cualquiera devuelva la suma elemento a elemento.

#### Ejemplo de ejecución

    > s = np.array([1,2,3])
    > t = np.array([4,5,6])
    > suma_matrices(s,t)
    
      [5 7 9]
     
_Sugerencia_: completa el código de la siguiente manera:

    def suma_matrices(a,b):
       ## --- TU CODIGO AQUI ---
       result = a + b
       return result

In [ ]:
def suma_matrices(matriz_a,matriz_b):
  matriz_suma=matriz_a+matriz_b
  return(matriz_suma)

comprueba manualmente tu código

In [ ]:
import numpy as np
a = np.random.randint(10, size=(3,2))
b = np.random.randint(10, size=(3,2))
print (a)
print (b)
print (suma_matrices(a,b))

[[2 2]
 [9 4]
 [8 9]]
[[0 7]
 [9 8]
 [7 8]]
[[ 2  9]
 [18 12]
 [15 17]]


#### registra tu solución en línea

In [ ]:
student.submit_task(globals(), task_id="task_01");

### Ejercicio 2: Realiza un cálculo 

En este ejercicio, al ejecutar la celda de más abajo, se generará una lista de número aleatorios.

Tendrás que calcular el valor promedio de la lista y asignarlo a la variable `avg` más abajo.

Puedes usar el método que quieras para realizar el cálculo (a mano, excel, python, etc.) lo que importa es el valor que obtengas.


In [ ]:
import numpy as np
rlist = np.random.randint(100, size=10)

#### tu solución

In [ ]:
import numpy as np
def promedio_lista(lista):
    promedio=np.mean(lista)
    return(promedio)
avg=promedio_lista(rlist)

#### registra tu solución en línea

In [ ]:
student.submit_task(globals(), task_id="task_02");